config/routes.rb
Ectf::Application.routes.draw do

  resources :results
  root :to => 'pages#home'

  devise_for :users
  match '/dashboard' => "dashboard#index", :as => :user_root

  get "pages/result"
  match "/ip" , to: "dashboard#ip"

end

app/models/filemanager.rb
class Filemanager < ActiveRecord::Base
	belongs_to :user
  attr_accessible :file, :level, :user_id
end

app/models/final.rb
class Final < ActiveRecord::Base
  belongs_to :user
  attr_accessible :score, :user_id
end

app/models/flags.rb
class Flags < ActiveRecord::Base
  # belongs_to :user
  attr_accessible :flag, :level, :user_id
end

app/models/ipaddress.rb
class Ipaddress < ActiveRecord::Base
  attr_accessible :ip, :team_name
end

app/models/load.rb
class Load < ActiveRecord::Base
  attr_accessible :loading
end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :hacked_id, :level_id, :type, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :filemanagers
	has_many :finals
  # has_many :flags
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me , :name , :ip
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!  
  def index
    @title = "Dashboard"
    const_time = $time #15 mins = 15*60=900sec
    # @clock = @time_past/const_time
    # $level = 0
    @time_rem = const_time - (Time.now - $time).to_i
    @loading = Load.find(1)
      @loading.save
    if @loading != true
      if @time_rem <= 600  && $level == 0#Check if the level is 0 and 15 mins are over !!
       #if yes then start loading next question!!
       @loading.loading = true
       @loading.save
       $level+=1
       $time = Time.now
       SendfileWorker.perform_async($level)
      elsif @time_rem <= 0  && $level == 1
        @loading.loading = true
       @loading.save
       $level+=1
       $time = Time.now
       SendfileWorker.perform_async($level)
       elsif @time_rem <= 0  && $level == 2
       @loading.loading = true
       @loading.save
       $level+=1
       $time = Time.now
       SendfileWorker.perform_async($level)
       elsif @time_rem <= 0  && $level == 3
       @loading.loading = true
       @loading.save
       $level+=1
       $time = Time.now
       SendfileWorker.perform_async($level)         
      end
    end
  	@time_rem = const_time - (Time.now - $time).to_i
    @sec = @time_rem%60
      # @loading.loading = false
    @user = User.all
  	# $level=0
  end

  def result
    @result = Result.new
  end

  def ip
    @ip = request.remote_ip
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def result
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def new
    @flag = Flags.all
  	@result = Result.new
  end

  def create
  	@ans = params[:result][:answer]
    if current_user.id != params[:result][:hacked_id].to_i
  	  @result = Result.find_or_create_by_user_id_and_hacked_id_and_level_id(current_user.id,params[:result][:hacked_id].to_i,$level)
    	if @result.answer == true
        flash[:notice] = "Already answered!!"
    		redirect_to results_path
    	else
     		@req_flag = Flags.where(level: $level,user_id: params[:result][:hacked_id]).first
    		puts "Answer = == #{@ans} &&& required === #{@req_flag}"
    		if @ans == @req_flag.flag
          #Making user marks updated
          final_result = Final.find_or_create_by_user_id(current_user.id)
          if final_result.score == nil
            final_result.score = 10
          else
            final_result.score += 10
          end
          final_result.save
  	  		@result.answer = true
    			@result.save
          flash[:notice] = "Correct Flag!!"
          redirect_to results_path
  	  	else
          flash[:notice] = "Wrong Flag!!"
    			redirect_to new_result_path
          # render 'new'
  	   	end
  	  end
    end
  end

  def index
    @result = Final.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/dashboard/index.html.erb
<div id="ectf" style="margin-left: -500px; width: 940px; top: 60%;" >
<div id="head">Dashboard
	<!--
<%= @time_rem %><br />
Sec = <%= @sec %>
level = <%= $level %>
-->

</div><br />
<div id="subhead" style="text-align: center;">    
<%  @user.each do |f| %>
<%= link_to f.name , "http://"+f.ip+"/ectf"  %><br /><br />
<% end %>
<!--
<%= @time_rem %><br />
Sec = <%= @sec %>
level = <%= $level %>
-->


</div><br />

</div>
<!-- --------------Timer is here--------------- -->
<div class="wrapper" >
	TIme left
        <div class="clock">
            <!-- Days -->
            <div class="clock_days">
                <div class="bgLayer">
                    <div class="topLayer"></div>
                    <canvas id="canvas_days" width="188" height="188">
                    </canvas>
                </div>
            </div>
            <!-- Days -->
            <!-- Hours -->
            <div class="clock_hours">
                <div class="bgLayer">
                    <div class="topLayer"></div>
                    <canvas id="canvas_hours" width="188" height="188">
                    </canvas>
                    <div class="text">
                        <p class="val">13</p>
                        <p class="type_hours">Hours</p>
                    </div>
                </div>
            </div>
            <!-- Hours -->
            <!-- Minutes -->
            <div class="clock_minutes">
                <div class="bgLayer">
                    <div class="topLayer"></div>
                    <canvas id="canvas_minutes" width="188" height="188">
                    </canvas>
                    <div class="text">
                        <p class="val">44</p>
                        <p class="type_minutes">Minutes</p>
                    </div>
                </div>
            </div>
            <!-- Minutes -->
            <!-- Seconds -->
            <div class="clock_seconds">
                <div class="bgLayer">
                    <div class="topLayer"></div>
                    <canvas id="canvas_seconds" width="188" height="188">
                    </canvas>
                    <div class="text">
                        <p class="val">21</p>
                        <p class="type_seconds">Seconds</p>
                    </div>
                </div>
            </div>
            <!-- Seconds -->
        </div>
        </div><!--/wrapper-->
<script type="text/javascript">
            $(document).ready(function(){
                JBCountDown({
                    secondsColor : "#ffdc50",
                    secondsGlow  : "none",

                    minutesColor : "#9cdb7d",
                    minutesGlow  : "none",

                    hoursColor   : "#378cff",
                    hoursGlow    : "none",

                    daysColor    : "#ff6565",
                    daysGlow     : "none",

                    startDate   : "900",
                    endDate     : "900",
                    now         : <%= 900 - @time_rem %>,
                    seconds     : <%= 60-@sec.to_i %>
                });
                $('.clock_days').remove();
                $('.clock_hours').remove();
            });
</script>

app/views/dashboard/ip.html.erb
<%= @ip %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="assets/style.css" />
</head>
  <title><%= @title %>|Ectf</title>
  <%= stylesheet_link_tag    "style" %>
  <% if @title == "Dashboard" %>
  <%= stylesheet_link_tag "jbclock" %>
  <%= javascript_include_tag "jquery-1.8.0.min" %>
   <%= javascript_include_tag "jbclock" %>
   <% end %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="links" style="background-color: black;padding-left:250px;font-size: 25px;">
		<%= button_to "Dashboard" , user_root_path , method: :get %>
<%= button_to "Results" , results_path , method: :get %>
<%= button_to "Submit Answer!" , new_result_path , method: :get %>
</div>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div id="ectf">
<div id="head">Welcome to ECTF</div><br />
<div id="subhead" style="text-align: center;">3rd Round</div><br />
<div id="login">
	<%= button_to "Login >>" , new_user_session_path , id: "login_btn" , methos: :get %>
</div>
</div>

app/views/pages/result.html.erb
<%= form_for() %>

app/views/results/create.html.erb
<%= @req_flag.flag %><br />
<%= @ans %>

app/views/results/index.html.erb
<div id="ectf">
<div id="head">Result</div><br />
<div id="subhead" style="text-align: center;">
	<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  	<div class="home">
    <div class="alert alert-<%= name == :notice ? "success" : "error" %> span7"> 
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
</div>
  <% end %>
<% end %>
<% @result.each do |f| %>
<%= f.user.name %>
<%= f.score %><br />
<% end %>


</div><br />

</div>

app/views/results/new.html.erb
<div id="ectf" style="margin-left: -150px;">
<div id="head">Submit keys</div><br />
<div id="subhead" style="text-align: center;">
	<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  	<div class="home">
    <div class="alert alert-<%= name == :notice ? "success" : "error" %> span7"> 
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
</div>
  <% end %>
<% end %>
<%= form_for(@result) do |f| %>
	<%= f.label :hacked_id , "Hacked account" %>
	<%= f.collection_select(:hacked_id, User.all, :id, :name) %><br />
	<%= f.label :answer , "Key" %>
	<%= f.text_field :answer %><br />
	<%= f.submit "Submit" %>
	<% end %>
</div><br />
</div>